dist: trusty
sudo: required
language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x

env:
  - PROXYSQL_IMAGE=percona/proxysql:1.4
  - PROXYSQL_IMAGE=perconalab/proxysql:1.3.6

services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
  - make format build testall

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
